version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - compose-bridge
    ports:
    - 3302:3306

  nodejs:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
       MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - compose-bridge
    ports:
      - 8080:3000
    volumes:
      - .:/var/www
      - ./node_modules:/var/www/node_modules

networks:
  compose-bridge:
    driver: bridge
